//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: student.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Student_StudentServiceClient`, then call methods of this protocol to make API calls.
internal protocol Student_StudentServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Student_StudentServiceClientInterceptorFactoryProtocol? { get }

  func findStuById(
    _ request: Student_FindByIdReqest,
    callOptions: CallOptions?
  ) -> UnaryCall<Student_FindByIdReqest, Student_StudentInfo>

  func findStudents(
    _ request: Student_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<Student_Empty, Student_StudentList>
}

extension Student_StudentServiceClientProtocol {
  internal var serviceName: String {
    return "student.StudentService"
  }

  /// Unary call to FindStuById
  ///
  /// - Parameters:
  ///   - request: Request to send to FindStuById.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func findStuById(
    _ request: Student_FindByIdReqest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Student_FindByIdReqest, Student_StudentInfo> {
    return self.makeUnaryCall(
      path: "/student.StudentService/FindStuById",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFindStuByIdInterceptors() ?? []
    )
  }

  /// Unary call to FindStudents
  ///
  /// - Parameters:
  ///   - request: Request to send to FindStudents.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func findStudents(
    _ request: Student_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Student_Empty, Student_StudentList> {
    return self.makeUnaryCall(
      path: "/student.StudentService/FindStudents",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFindStudentsInterceptors() ?? []
    )
  }
}

internal protocol Student_StudentServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'findStuById'.
  func makeFindStuByIdInterceptors() -> [ClientInterceptor<Student_FindByIdReqest, Student_StudentInfo>]

  /// - Returns: Interceptors to use when invoking 'findStudents'.
  func makeFindStudentsInterceptors() -> [ClientInterceptor<Student_Empty, Student_StudentList>]
}

internal final class Student_StudentServiceClient: Student_StudentServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Student_StudentServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the student.StudentService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Student_StudentServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

